name: Deploy QuickTrip
# This is just a display name for your workflow

on:
  push:
    branches: [main] # Triggers when you push to main branch
  pull_request:
    branches: [main] # Triggers when PRs are made to main

jobs:
  build-and-deploy: # Job name (you can change this)
    runs-on: ubuntu-latest # Uses Ubuntu virtual machine

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Downloads your repo code

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Installs Node.js
        with:
          node-version: "18" # Specify Node version
          cache: "npm" # Caches npm dependencies for faster builds

      - name: Install dependencies
        run: npm ci # npm ci is faster/more reliable than npm install

      - name: Build
        run: npm run build # Runs your build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Third-party action for GH Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Auto-provided by GitHub
          publish_dir: ./build # Where your built files are located
